// Automatically generated by Packet Go code generator.
package openflow_meta

import (
	"encoding/binary"
	"errors"
	"fmt"
	"net"

	"github.com/packet/packet/src/go/packet"

	"github.com/soheilhy/beehive/openflow/openflowv10"
	"github.com/soheilhy/beehive/openflow/openflowv12"
)
